// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Env int32

const (
	Env_ENV_UNSPECIFIED Env = 0
	Env_ENV_DEV         Env = 1
	Env_ENV_STAGING     Env = 2
	Env_ENV_PROD        Env = 3
)

// Enum value maps for Env.
var (
	Env_name = map[int32]string{
		0: "ENV_UNSPECIFIED",
		1: "ENV_DEV",
		2: "ENV_STAGING",
		3: "ENV_PROD",
	}
	Env_value = map[string]int32{
		"ENV_UNSPECIFIED": 0,
		"ENV_DEV":         1,
		"ENV_STAGING":     2,
		"ENV_PROD":        3,
	}
)

func (x Env) Enum() *Env {
	p := new(Env)
	*p = x
	return p
}

func (x Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Env) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Env) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[0]
}

func (x Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Env.Descriptor instead.
func (Env) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

// TODO 服务注册 & 发现
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           Env                    `protobuf:"varint,1,opt,name=env,proto3,enum=kratos.api.Env" json:"env,omitempty"`
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Observability *Observability         `protobuf:"bytes,4,opt,name=observability,proto3" json:"observability,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	Registry      *Registry              `protobuf:"bytes,6,opt,name=registry,proto3" json:"registry,omitempty"`
	Scheduler     *Scheduler             `protobuf:"bytes,7,opt,name=scheduler,proto3" json:"scheduler,omitempty"`
	App           *App                   `protobuf:"bytes,15,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetEnv() Env {
	if x != nil {
		return x.Env
	}
	return Env_ENV_UNSPECIFIED
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetScheduler() *Scheduler {
	if x != nil {
		return x.Scheduler
	}
	return nil
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Observability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         *Observability_Trace   `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	Metrics       *Observability_Metrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Log           *Observability_Log     `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Observability) GetTrace() *Observability_Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Observability) GetMetrics() *Observability_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Observability) GetLog() *Observability_Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type Auth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenPrivateKey string                 `protobuf:"bytes,1,opt,name=token_private_key,json=tokenPrivateKey,proto3" json:"token_private_key,omitempty"`
	TokenPublicKey  string                 `protobuf:"bytes,2,opt,name=token_public_key,json=tokenPublicKey,proto3" json:"token_public_key,omitempty"`
	TokenTtl        *durationpb.Duration   `protobuf:"bytes,3,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Auth) GetTokenPrivateKey() string {
	if x != nil {
		return x.TokenPrivateKey
	}
	return ""
}

func (x *Auth) GetTokenPublicKey() string {
	if x != nil {
		return x.TokenPublicKey
	}
	return ""
}

func (x *Auth) GetTokenTtl() *durationpb.Duration {
	if x != nil {
		return x.TokenTtl
	}
	return nil
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consul        *Registry_Consul       `protobuf:"bytes,1,opt,name=consul,proto3" json:"consul,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Registry) GetConsul() *Registry_Consul {
	if x != nil {
		return x.Consul
	}
	return nil
}

type Scheduler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithSeconds   bool                   `protobuf:"varint,1,opt,name=with_seconds,json=withSeconds,proto3" json:"with_seconds,omitempty"`
	Jobs          *Scheduler_Jobs        `protobuf:"bytes,2,opt,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scheduler) Reset() {
	*x = Scheduler{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scheduler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scheduler) ProtoMessage() {}

func (x *Scheduler) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scheduler.ProtoReflect.Descriptor instead.
func (*Scheduler) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Scheduler) GetWithSeconds() bool {
	if x != nil {
		return x.WithSeconds
	}
	return false
}

func (x *Scheduler) GetJobs() *Scheduler_Jobs {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RealIp        *Server_HTTP_RealIP    `protobuf:"bytes,4,opt,name=real_ip,json=realIp,proto3" json:"real_ip,omitempty"`
	Cors          *Server_HTTP_CORS      `protobuf:"bytes,5,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_HTTP) GetRealIp() *Server_HTTP_RealIP {
	if x != nil {
		return x.RealIp
	}
	return nil
}

func (x *Server_HTTP) GetCors() *Server_HTTP_CORS {
	if x != nil {
		return x.Cors
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_HTTP_RealIP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 包含客户端 IP 的 http header
	IpHeaders []string `protobuf:"bytes,1,rep,name=ip_headers,json=ipHeaders,proto3" json:"ip_headers,omitempty"`
	// 受信任的下游代理 CIDR/IP
	TrustedProxies []string `protobuf:"bytes,2,rep,name=trusted_proxies,json=trustedProxies,proto3" json:"trusted_proxies,omitempty"`
	// maybe from CDN
	TrustedHeader string `protobuf:"bytes,3,opt,name=trusted_header,json=trustedHeader,proto3" json:"trusted_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP_RealIP) Reset() {
	*x = Server_HTTP_RealIP{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP_RealIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP_RealIP) ProtoMessage() {}

func (x *Server_HTTP_RealIP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP_RealIP.ProtoReflect.Descriptor instead.
func (*Server_HTTP_RealIP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Server_HTTP_RealIP) GetIpHeaders() []string {
	if x != nil {
		return x.IpHeaders
	}
	return nil
}

func (x *Server_HTTP_RealIP) GetTrustedProxies() []string {
	if x != nil {
		return x.TrustedProxies
	}
	return nil
}

func (x *Server_HTTP_RealIP) GetTrustedHeader() string {
	if x != nil {
		return x.TrustedHeader
	}
	return ""
}

type Server_HTTP_CORS struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowCredentials bool                   `protobuf:"varint,1,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	AllowedHeaders   []string               `protobuf:"bytes,2,rep,name=allowed_headers,json=allowedHeaders,proto3" json:"allowed_headers,omitempty"`
	AllowedMethods   []string               `protobuf:"bytes,3,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`
	AllowedOrigins   []string               `protobuf:"bytes,4,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Server_HTTP_CORS) Reset() {
	*x = Server_HTTP_CORS{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP_CORS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP_CORS) ProtoMessage() {}

func (x *Server_HTTP_CORS) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP_CORS.ProtoReflect.Descriptor instead.
func (*Server_HTTP_CORS) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *Server_HTTP_CORS) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Server_HTTP_CORS) GetAllowedHeaders() []string {
	if x != nil {
		return x.AllowedHeaders
	}
	return nil
}

func (x *Server_HTTP_CORS) GetAllowedMethods() []string {
	if x != nil {
		return x.AllowedMethods
	}
	return nil
}

func (x *Server_HTTP_CORS) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Schema        string                 `protobuf:"bytes,6,opt,name=schema,proto3" json:"schema,omitempty"`
	Params        string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Migrate       *Data_Database_Migrate `protobuf:"bytes,20,opt,name=migrate,proto3" json:"migrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Database) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Database) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Database) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Data_Database) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Data_Database) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Data_Database) GetMigrate() *Data_Database_Migrate {
	if x != nil {
		return x.Migrate
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,7,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type Data_Database_Migrate struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// 是否运行迁移
	Run bool `protobuf:"varint,2,opt,name=run,proto3" json:"run,omitempty"`
	// 迁移完成是否直接退出
	Only          bool `protobuf:"varint,3,opt,name=only,proto3" json:"only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database_Migrate) Reset() {
	*x = Data_Database_Migrate{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database_Migrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database_Migrate) ProtoMessage() {}

func (x *Data_Database_Migrate) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database_Migrate.ProtoReflect.Descriptor instead.
func (*Data_Database_Migrate) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Data_Database_Migrate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database_Migrate) GetRun() bool {
	if x != nil {
		return x.Run
	}
	return false
}

func (x *Data_Database_Migrate) GetOnly() bool {
	if x != nil {
		return x.Only
	}
	return false
}

type Observability_Trace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host:port grpc endpoint
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// 生产环境采样率，仅生产环境
	ProductionSampleRate float32 `protobuf:"fixed32,2,opt,name=production_sample_rate,json=productionSampleRate,proto3" json:"production_sample_rate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Observability_Trace) Reset() {
	*x = Observability_Trace{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Trace) ProtoMessage() {}

func (x *Observability_Trace) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Trace.ProtoReflect.Descriptor instead.
func (*Observability_Trace) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Observability_Trace) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Trace) GetProductionSampleRate() float32 {
	if x != nil {
		return x.ProductionSampleRate
	}
	return 0
}

type Observability_Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// grpc endpoint
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability_Metrics) Reset() {
	*x = Observability_Metrics{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Metrics) ProtoMessage() {}

func (x *Observability_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Metrics.ProtoReflect.Descriptor instead.
func (*Observability_Metrics) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Observability_Metrics) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Observability_Log struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DEBUG, INFO, WARN, ERROR, FATAL
	// 如果空或无效值结果为 INFO
	Level         string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability_Log) Reset() {
	*x = Observability_Log{}
	mi := &file_conf_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Log) ProtoMessage() {}

func (x *Observability_Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Log.ProtoReflect.Descriptor instead.
func (*Observability_Log) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Observability_Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Registry_Consul struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry_Consul) Reset() {
	*x = Registry_Consul{}
	mi := &file_conf_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry_Consul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry_Consul) ProtoMessage() {}

func (x *Registry_Consul) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry_Consul.ProtoReflect.Descriptor instead.
func (*Registry_Consul) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Registry_Consul) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Registry_Consul) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

type Scheduler_Jobs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scheduler_Jobs) Reset() {
	*x = Scheduler_Jobs{}
	mi := &file_conf_conf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scheduler_Jobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scheduler_Jobs) ProtoMessage() {}

func (x *Scheduler_Jobs) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scheduler_Jobs.ProtoReflect.Descriptor instead.
func (*Scheduler_Jobs) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6, 0}
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xf1\x02\n" +
	"\tBootstrap\x12!\n" +
	"\x03env\x18\x01 \x01(\x0e2\x0f.kratos.api.EnvR\x03env\x12*\n" +
	"\x06server\x18\x02 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.kratos.api.DataR\x04data\x12?\n" +
	"\robservability\x18\x04 \x01(\v2\x19.kratos.api.ObservabilityR\robservability\x12$\n" +
	"\x04auth\x18\x05 \x01(\v2\x10.kratos.api.AuthR\x04auth\x120\n" +
	"\bregistry\x18\x06 \x01(\v2\x14.kratos.api.RegistryR\bregistry\x123\n" +
	"\tscheduler\x18\a \x01(\v2\x15.kratos.api.SchedulerR\tscheduler\x12!\n" +
	"\x03app\x18\x0f \x01(\v2\x0f.kratos.api.AppR\x03app\"\xce\x05\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1a\xfe\x03\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x127\n" +
	"\areal_ip\x18\x04 \x01(\v2\x1e.kratos.api.Server.HTTP.RealIPR\x06realIp\x120\n" +
	"\x04cors\x18\x05 \x01(\v2\x1c.kratos.api.Server.HTTP.CORSR\x04cors\x1aw\n" +
	"\x06RealIP\x12\x1d\n" +
	"\n" +
	"ip_headers\x18\x01 \x03(\tR\tipHeaders\x12'\n" +
	"\x0ftrusted_proxies\x18\x02 \x03(\tR\x0etrustedProxies\x12%\n" +
	"\x0etrusted_header\x18\x03 \x01(\tR\rtrustedHeader\x1a\xae\x01\n" +
	"\x04CORS\x12+\n" +
	"\x11allow_credentials\x18\x01 \x01(\bR\x10allowCredentials\x12'\n" +
	"\x0fallowed_headers\x18\x02 \x03(\tR\x0eallowedHeaders\x12'\n" +
	"\x0fallowed_methods\x18\x03 \x03(\tR\x0eallowedMethods\x12'\n" +
	"\x0fallowed_origins\x18\x04 \x03(\tR\x0eallowedOrigins\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xac\x05\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a\xc0\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06schema\x18\x06 \x01(\tR\x06schema\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12;\n" +
	"\amigrate\x18\x14 \x01(\v2!.kratos.api.Data.Database.MigrateR\amigrate\x1aG\n" +
	"\aMigrate\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x10\n" +
	"\x03run\x18\x02 \x01(\bR\x03run\x12\x12\n" +
	"\x04only\x18\x03 \x01(\bR\x04only\x1a\xfb\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\a \x01(\x05R\x02db\"\xd3\x02\n" +
	"\rObservability\x125\n" +
	"\x05trace\x18\x01 \x01(\v2\x1f.kratos.api.Observability.TraceR\x05trace\x12;\n" +
	"\ametrics\x18\x02 \x01(\v2!.kratos.api.Observability.MetricsR\ametrics\x12/\n" +
	"\x03log\x18\x03 \x01(\v2\x1d.kratos.api.Observability.LogR\x03log\x1aY\n" +
	"\x05Trace\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x124\n" +
	"\x16production_sample_rate\x18\x02 \x01(\x02R\x14productionSampleRate\x1a%\n" +
	"\aMetrics\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x1a\x1b\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"\x94\x01\n" +
	"\x04Auth\x12*\n" +
	"\x11token_private_key\x18\x01 \x01(\tR\x0ftokenPrivateKey\x12(\n" +
	"\x10token_public_key\x18\x02 \x01(\tR\x0etokenPublicKey\x126\n" +
	"\ttoken_ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\btokenTtl\"{\n" +
	"\bRegistry\x123\n" +
	"\x06consul\x18\x01 \x01(\v2\x1b.kratos.api.Registry.ConsulR\x06consul\x1a:\n" +
	"\x06Consul\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\"f\n" +
	"\tScheduler\x12!\n" +
	"\fwith_seconds\x18\x01 \x01(\bR\vwithSeconds\x12.\n" +
	"\x04jobs\x18\x02 \x01(\v2\x1a.kratos.api.Scheduler.JobsR\x04jobs\x1a\x06\n" +
	"\x04Jobs\"\x05\n" +
	"\x03App*F\n" +
	"\x03Env\x12\x13\n" +
	"\x0fENV_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aENV_DEV\x10\x01\x12\x0f\n" +
	"\vENV_STAGING\x10\x02\x12\f\n" +
	"\bENV_PROD\x10\x03B7Z5github.com/go-kratos/kratos-layout/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_conf_conf_proto_goTypes = []any{
	(Env)(0),                      // 0: kratos.api.Env
	(*Bootstrap)(nil),             // 1: kratos.api.Bootstrap
	(*Server)(nil),                // 2: kratos.api.Server
	(*Data)(nil),                  // 3: kratos.api.Data
	(*Observability)(nil),         // 4: kratos.api.Observability
	(*Auth)(nil),                  // 5: kratos.api.Auth
	(*Registry)(nil),              // 6: kratos.api.Registry
	(*Scheduler)(nil),             // 7: kratos.api.Scheduler
	(*App)(nil),                   // 8: kratos.api.App
	(*Server_HTTP)(nil),           // 9: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),           // 10: kratos.api.Server.GRPC
	(*Server_HTTP_RealIP)(nil),    // 11: kratos.api.Server.HTTP.RealIP
	(*Server_HTTP_CORS)(nil),      // 12: kratos.api.Server.HTTP.CORS
	(*Data_Database)(nil),         // 13: kratos.api.Data.Database
	(*Data_Redis)(nil),            // 14: kratos.api.Data.Redis
	(*Data_Database_Migrate)(nil), // 15: kratos.api.Data.Database.Migrate
	(*Observability_Trace)(nil),   // 16: kratos.api.Observability.Trace
	(*Observability_Metrics)(nil), // 17: kratos.api.Observability.Metrics
	(*Observability_Log)(nil),     // 18: kratos.api.Observability.Log
	(*Registry_Consul)(nil),       // 19: kratos.api.Registry.Consul
	(*Scheduler_Jobs)(nil),        // 20: kratos.api.Scheduler.Jobs
	(*durationpb.Duration)(nil),   // 21: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	0,  // 0: kratos.api.Bootstrap.env:type_name -> kratos.api.Env
	2,  // 1: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	3,  // 2: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	4,  // 3: kratos.api.Bootstrap.observability:type_name -> kratos.api.Observability
	5,  // 4: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	6,  // 5: kratos.api.Bootstrap.registry:type_name -> kratos.api.Registry
	7,  // 6: kratos.api.Bootstrap.scheduler:type_name -> kratos.api.Scheduler
	8,  // 7: kratos.api.Bootstrap.app:type_name -> kratos.api.App
	9,  // 8: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	10, // 9: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	13, // 10: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	14, // 11: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	16, // 12: kratos.api.Observability.trace:type_name -> kratos.api.Observability.Trace
	17, // 13: kratos.api.Observability.metrics:type_name -> kratos.api.Observability.Metrics
	18, // 14: kratos.api.Observability.log:type_name -> kratos.api.Observability.Log
	21, // 15: kratos.api.Auth.token_ttl:type_name -> google.protobuf.Duration
	19, // 16: kratos.api.Registry.consul:type_name -> kratos.api.Registry.Consul
	20, // 17: kratos.api.Scheduler.jobs:type_name -> kratos.api.Scheduler.Jobs
	21, // 18: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	11, // 19: kratos.api.Server.HTTP.real_ip:type_name -> kratos.api.Server.HTTP.RealIP
	12, // 20: kratos.api.Server.HTTP.cors:type_name -> kratos.api.Server.HTTP.CORS
	21, // 21: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	15, // 22: kratos.api.Data.Database.migrate:type_name -> kratos.api.Data.Database.Migrate
	21, // 23: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	21, // 24: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		EnumInfos:         file_conf_conf_proto_enumTypes,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
