// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/biz"
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/data"
	"github.com/go-kratos/kratos-layout/internal/server"
	"github.com/go-kratos/kratos-layout/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, env *conf.Env, confServer *conf.Server, confData *conf.Data, observability *conf.Observability, registry *conf.Registry, auth *conf.Auth) (*kratos.App, func(), error) {
	registrar := data.NewRegistrar(registry)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	versionService := service.NewVersionService()
	grpcServer := server.NewGRPCServer(confServer, logger, greeterService, versionService)
	httpServer := server.NewHTTPServer(confServer, logger, greeterService, versionService)
	background := server.NewBackground(logger)
	scheduler := server.NewScheduler(logger)
	app := newApp(logger, registrar, grpcServer, httpServer, background, scheduler)
	return app, func() {
		cleanup()
	}, nil
}
