// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.0
// source: version/v1/version.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationVersionGetVersion = "/api.version.v1.Version/GetVersion"

type VersionHTTPServer interface {
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionReply, error)
}

func RegisterVersionHTTPServer(s *http.Server, srv VersionHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/version", _Version_GetVersion0_HTTP_Handler(srv))
}

func _Version_GetVersion0_HTTP_Handler(srv VersionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVersionGetVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVersion(ctx, req.(*GetVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetVersionReply)
		return ctx.Result(200, reply)
	}
}

type VersionHTTPClient interface {
	GetVersion(ctx context.Context, req *GetVersionRequest, opts ...http.CallOption) (rsp *GetVersionReply, err error)
}

type VersionHTTPClientImpl struct {
	cc *http.Client
}

func NewVersionHTTPClient(client *http.Client) VersionHTTPClient {
	return &VersionHTTPClientImpl{client}
}

func (c *VersionHTTPClientImpl) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...http.CallOption) (*GetVersionReply, error) {
	var out GetVersionReply
	pattern := "/v1/version"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationVersionGetVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
